name: Development Builds

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [16]
        gradle: [7.1]
    container:
      image: gradle:${{ matrix.gradle }}-jdk${{ matrix.java }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cache Gradle packages
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Loom Files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/*gradle*', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: Build with Gradle
        run: gradle clean build -x check --stacktrace --no-daemon
      - name: Upload Main JARs
        uses: actions/upload-artifact@v2.2.0
        if: ${{ !env.ACT }}
        with:
          name: quickcarpet-jars
          path: build/libs/*.jar
      - name: Upload API JARs
        uses: actions/upload-artifact@v2.2.0
        if: ${{ !env.ACT }}
        with:
          name: quickcarpet-api-jars
          path: api/build/libs/*.jar
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        java: [16]
        gradle: [7.1]
    container:
      image: gradle:${{ matrix.gradle }}-jdk${{ matrix.java }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cache Gradle packages
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Loom Files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/*gradle*', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: Run Unit Tests
        run: gradle test --stacktrace --no-daemon
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always() && !env.ACT
        with:
          files: build/test-results/**/*.xml
  game-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        java: [16]
        gradle: [7.1]
    container:
      image: gradle:${{ matrix.gradle }}-jdk${{ matrix.java }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cache Gradle packages
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Loom Files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/*gradle*', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: Run Game Tests
        run: gradle runTestServer --stacktrace --no-daemon
      - name: Publish Test World
        uses: actions/upload-artifact@v2.2.0
        if: always() && !env.ACT
        with:
          name: gametestworld
          path: run/gametestworld/*
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always() && !env.ACT
        with:
          files: build/test-results/**/*.xml
  game-test-with-mods:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        java: [16]
        gradle: [7.1]
        lithium: [mc1.17.1-0.7.3]
    container:
      image: gradle:${{ matrix.gradle }}-jdk${{ matrix.java }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cache Gradle packages
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Loom Files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/*gradle*', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: Download Mods
        run: |
          mkdir -p run/mods/
          cd run/mods/
          wget https://github.com/CaffeineMC/lithium-fabric/releases/download/${{ matrix.lithium }}/lithium-fabric-${{ matrix.lithium }}.jar
      - name: Run Game Tests
        run: gradle runTestServer --stacktrace --no-daemon
      - name: Publish Test World
        uses: actions/upload-artifact@v2.2.0
        if: always() && !env.ACT
        with:
          name: gametestworld-mods
          path: run/gametestworld/*
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always() && !env.ACT
        with:
          files: build/test-results/**/*.xml